### ISSUE TITLE
Economy Rate incorrect error 

### ISSUE THREAD

**Issue by ald0405** [robjhyndman/cricketdata#12]
```
fetch_cricinfo( "ODI", "Men", "Bowling", type = "innings")
```
Error in clean_bowling_data(this_data) : Economy rate incorrect

**Comment by sariya** [comment]
i get the same error. 

@robjhyndman  - I'd be happy to dig into this, but haven't worked with parsing before. Any pointers here?

**Comment by robjhyndman** [comment]
The error is occurring in clean_bowling_data line 78. It seems to occur when there were 8 ball overs in Australia, but the ER is computed as if there were 6 ball overs. I've now fixed the problem in https://github.com/ropenscilabs/cricketdata/commit/93794ab5e215b3e4c55b7d97280fd96ebc4f9d7e
