### ISSUE TITLE
Match df for IPL 

### ISSUE THREAD

**Issue by Dazzalytics** [robjhyndman/cricketdata#22]
Hello! The fetch_cricsheet function to get the match df for IPL is returning df with lists for team names & possibly other columns as well. This makes doing further analysis a little tricky. Any help is appreciated! 

The warning message after getting the match data is as follows:

Values from `value` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = {summary_fun}` to summarise duplicates.
* Use the following dplyr code to identify duplicates.
  {data} %>%
    dplyr::group_by(match_id, key) %>%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
    dplyr::filter(n > 1L)

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/cricketdata/commit/4a5e1cd0e3f9459216e2ba2df8e45c4075bb9127
