### ISSUE TITLE
Assigned data `as.numeric(tab$Mins)` must be compatible with existing data.

### ISSUE THREAD

**Issue by myaseen208** [robjhyndman/cricketdata#26]
The code given below:

```
library(cricketdata)
library(tidyverse)
library(stringi)

df1 <-
  fetch_player_data(
      playerid  = find_player_id(searchstring = "Shaheen Shah Afridi")$ID
    , matchtype = c("test", "odi", "t20")[1]
    , activity  = c("batting", "bowling", "fielding")[2]
    )

```

producing the following error:

> Error:
> ! Assigned data `as.numeric(tab$Mins)` must be compatible with existing data.
> ✖ Existing data has 43 rows.
> ✖ Assigned data has 0 rows.
> ℹ Only vectors of size 1 are recycled.
> Run `rlang::last_error()` to see where the error occurred.
> Warning message:
> Unknown or uninitialised column: `Mins`. 
>

**Comment by neilfws** [comment]
> The code given below:
>...
> producing the following error:

I'm seeing the same error using "Cameron Green" as the player. The error occurs when activity = anything other than batting.

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/cricketdata/commit/138e4471379dd05585c316dd3d0f7ea7ff9ae942

**Comment by myaseen208** [comment]
Thanks
