### ISSUE TITLE
Hex logo / sticker

### ISSUE THREAD

**Issue by jacquietran** [robjhyndman/cricketdata#28]
@Dazzalytics contacted me about designing a hex logo for this package - creating an issue to log the idea and process.

Got an idea I'm working on - will post a draft below shortly.

**Comment by jacquietran** [comment]
how about something like this?

![hex-cricketdata-sample-20230104](https://user-images.githubusercontent.com/10459045/210488569-184bd1fc-cf3c-4942-b85d-e32cccaf6f15.png)

**Comment by robjhyndman** [comment]
Looks great. Can you up the resolution a little?

**Comment by jacquietran** [comment]
i can increase the resolution of the overall logo, although the image in the middle is intentionally pixelated / noisy.

i was going to do a little vector illustration from a reference image but went for pixelation as a faster (lazy) option 😆 should i perhaps try the vector illustration instead?

**Comment by robjhyndman** [comment]
Maybe. I don't mind the pixelation as such, but the combination with noise makes it look like an error. Perhaps try a vector approach, or remove the noise? I'm not great with design, so I wouldn't take too much notice of what I think!

**Comment by jacquietran** [comment]
ahh yeah i understand. here's a version without noise:

![hex-cricketdata-sample-20230104-02](https://user-images.githubusercontent.com/10459045/210492259-9c7b9834-2e27-4f57-90e7-bfb544fbf384.png)

**Comment by Dazzalytics** [comment]
@jacquietran thank you for taking the lead on this! The draft looks good. If possible, it would be interesting to see a player in whites with a red ball and maybe a red outline on the hexagonal boundary.

**Comment by Dazzalytics** [comment]
Very Nice! My vote is for the test whites version! 
@jacquietran great work!

**Comment by Dazzalytics** [comment]
Can we add it to the package website and possibly announce it publicly? 
Perhaps @jacquietran can introduce it on Twitter once we have added it to the website.

**Comment by robjhyndman** [comment]
Now added to the package website.

**Comment by jacquietran** [comment]
Awesome, thanks Rob for using the logo and to you both for the feedback! Will post on socials now.
