### ISSUE TITLE
Unable to load package in R

### ISSUE THREAD

**Issue by adisrir** [robjhyndman/cricketdata#34]
When installing cricket data package this error is occurring

ERROR: unable to collate and parse R files for package ‘cricketdata’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cricketdata’
Warning in install.packages :
  installation of package ‘cricketdata’ had non-zero exit status

**Comment by robjhyndman** [comment]
Are you installing from CRAN or github? More details are required. No-one else has reported a similar problem.

**Comment by adisrir** [comment]
> Are you installing from CRAN or github? More details are required. No-one else has reported a similar problem.

Tried installing from CRAN and github and having same error.

* installing *source* package ‘cricketdata’ ...
** package ‘cricketdata’ successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) : 
  /private/var/folders/f4/5bfrbqf534q_37ddkyvyj2dw0000gn/T/RtmpR4pbEH/R.INSTALL125c919e16ebd/cricketdata/R/countries.R:54:82: unexpected '>'
53: 
54: men <- tibble::as_tibble(men[order(men$name), ], .name_repair = "check_unique") |>
                                                                                     ^
ERROR: unable to collate and parse R files for package ‘cricketdata’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cricketdata’
Warning in install.packages :
  installation of package ‘cricketdata’ had non-zero exit status
  
  
  There seems to be an error with line 54

**Comment by robjhyndman** [comment]
I think the issue is that your version of R is too old and does not recognize the native pipe `|>`. It was introduced more than 2 years ago.
