### ISSUE TITLE
Missing BBL games

### ISSUE THREAD

**Issue by lincolntracy** [robjhyndman/cricketdata#36]
Hi there,

I've been working with the BBL data recently and noticed there are certain games that aren't included in the `fetch_cricsheet` command for one or both of the match or ball-by-ball types (see list below) - is there something that needs to be addressed to include these games?

Adelaide Strikers v Brisbane Heat (BBL01 - 03/01/2012)
Brisbane Heat v Hobart Hurricanes (BBL01 - 06/01/2012)
Melbourne Stars v Melbourne Renegades (BBL01 - 07/01/2012)
Sydney Thunder v Perth Scorchers (BBL01 - 11/01/2012)
Melbourne Stars v Sydney Sixers (BBL02 - 21/12/2012)
Hobart Hurricanes v Sydney Thunder (BBL02 - 23/12/2012)
Hobart Hurricanes v Perth Scorchers (BBL02 - 01/01/2013)
Brisbane Heat v Melbourne Stars (BBL02 - 03/01/2013)
Adelaide Strikers v Hobart Hurricanes (BBL02 - 05/01/2013)
Melbourne Renegades v Sydney Sixers (BBL02 - 09/01/2013)
Perth Scorchers v Adelaide Strikers (BBL03 - 31/12/2013)
Sydney Thunder v Hobart Hurricanes (BBL04 - 09/01/2015)
Melbourne Stars v Perth Scorchers (BBL05 - 16/01/2016)
Melbourne Stars v Sydney Thunder (BBL05 - 20/12/2015)
Sydney Thunder v Sydney Sixers (BBL05 - 17/12/2015)

Cheers,
Lincoln

**Comment by robjhyndman** [comment]
fetch_cricsheet grabs the data from https://cricsheet.org/downloads/ and wrangles it into a form suitable for analysis in R. Are the data sets you want available on that page? If not, perhaps ask the people who run cricsheet. If the data are available there, then it is a problem with the cricketdata package, and I will take a look.

**Comment by lincolntracy** [comment]
Thanks for pointing that out, Rob. It seems the data for these matches are missing from cricsheet, so I'll try asking them about it.
