### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ab0408** [robjhyndman/cricketdata#37]
Hi

Have tried running some of the sample code in your overview page (fetch_cricinfo("T20", "Women", "Bowling") for instance)

I am consistently getting the below error. Any idea what may be driving this?

Separately I saw in another thread that you mentioned cricinfo had been blocking the data download - is this related?

Thanks
Aritra 

test_cricinfo = fetch_cricinfo(matchtype = "test", sex = "men", activity = "batting"
+                , type = "career")

Error in cli::cli_progress_update() :                        
  Cannot find current progress bar for `<environment: 0x00000284702cea10>`

> test_cricinfo
Error: object 'test_cricinfo' not found
> wt20 <- fetch_cricinfo("T20", "Women", "Bowling")
Error in cli::cli_progress_update() :                        
  Cannot find current progress bar for `<environment: 0x000002846a832788>`
>

**Comment by robjhyndman** [comment]
Try installing the current github version using 

```r
devtools::install_github("robjhyndman/cricketdata")
```

The cricinfo problem is different from this issue, and it seems to now be working ok.

**Comment by ab0408** [comment]
Thanks. Still getting the same error. But I think I should be able to derive the cricinfo table you list in your overview page with the cricsheets functions. Very useful and interesting package!

Error in cli::cli_progress_update() :                        
  Cannot find current progress bar for `<environment: 0x0000028472a82410>`

**Comment by cddesja** [comment]
@ab0408, I was getting this error as well, but after updating the `cli` package and the dependencies of `cricketdata` this error went away for me.

I wonder if commenting out lines 54, 60, and 65 in the `fetch_cricket_data` function would solve this for you too? Or, if you're on an older version, all references to `cli`?

If it does work, I wonder if `cli` could be an argument that defaults to `TRUE` for the `fetch_cricinfo` function?
