### ISSUE TITLE
Unable to call any function

### ISSUE THREAD

**Issue by akshay076** [robjhyndman/cricketdata#38]
Hi, I have the latest version of R and RStudio and installed the package from GitHub `devtools::install_github("robjhyndman/cricketdata")`

However, I am still getting an error on all functions stating not found. Are there any steps I am missing?
```
> mtests <- fetch_cricinfo("Tests", "Men", "Batting", "India")
Error in fetch_cricinfo("Tests", "Men", "Batting", "India") : 
  could not find function "fetch_cricinfo"
```

**Comment by robjhyndman** [comment]
You have to load the `cricketdata` package, before you can use it.

```r
library(cricketdata)
```

**Comment by akshay076** [comment]
I just noticed I was being dumb. Thanks and appreciate the quick reply.
