### ISSUE TITLE
Error in fetch_cricinfo()

### ISSUE THREAD

**Issue by manohar8** [robjhyndman/cricketdata#39]
Post downloading the cricketdata package get the follwing error while fetching data with fetch_cricinfo()

Error in cli::cli_progress_update() :                        
  Cannot find current progress bar for `<environment: 0x000001ea910c70a8>`

Thanks
MD

**Comment by robjhyndman** [comment]
Update to the current dev version. This is probably the error that was fixed in https://github.com/robjhyndman/cricketdata/commit/dedb9d26a05accda745415935263d0f57c141a2b.

**Comment by achinthaeyepax** [comment]
Installed the dev version and it worked.
`
install.packages(c("devtools"))
library(devtools)
devtools::install_github("robjhyndman/cricketdata")
library(tidyverse)
`
